# Generated by Django 2.2.7 on 2019-11-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='retard',
            field=models.IntegerField(default=0),
        ),
    ]
