# Generated by Django 2.2.7 on 2019-11-21 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20191121_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nb_autres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='nb_livres',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Profile'),
        ),
    ]
