# Generated by Django 2.2.7 on 2019-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20191125_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='lien',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
