# Generated by Django 2.2.7 on 2019-11-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20191128_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name="Photo de l'auteur"),
        ),
    ]
