# Generated by Django 2.2.7 on 2019-11-19 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=45)),
                ('prénom', models.CharField(max_length=45)),
                ('statut', models.CharField(max_length=45)),
                ('nb_livres', models.IntegerField(blank=True, null=True)),
                ('nb_autres', models.IntegerField(blank=True, null=True)),
                ('nb_retards', models.IntegerField(blank=True, null=True)),
                ('bad_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id_ouvrage', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=45)),
                ('titre', models.CharField(max_length=45)),
                ('auteur', models.CharField(max_length=45)),
                ('genre', models.CharField(max_length=45)),
                ('disponible', models.IntegerField()),
                ('autorisé', models.IntegerField()),
            ],
            options={
                'db_table': 'Ouvrages',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('id_client', models.IntegerField()),
                ('type', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('prix', models.FloatField()),
            ],
            options={
                'db_table': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('statut', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('prix', models.IntegerField()),
            ],
            options={
                'db_table': 'Tarifs',
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id_emprunt', models.AutoField(primary_key=True, serialize=False)),
                ('date_emprunt', models.DateTimeField()),
                ('retard', models.IntegerField()),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Client')),
                ('ouvrage', models.ForeignKey(db_column='id_ouvrage', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.Ouvrage')),
            ],
            options={
                'db_table': 'Emprunts',
            },
        ),
    ]
