# Generated by Django 2.2.7 on 2019-11-19 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0002_auto_20191119_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id_auteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prénom', models.CharField(max_length=100)),
                ('naissance', models.DateTimeField(blank=True, null=True)),
                ('mort', models.DateTimeField(blank=True, null=True, verbose_name='Mort')),
            ],
        ),
        migrations.AlterModelOptions(
            name='emprunt',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='client',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='id_client',
        ),
        migrations.AddField(
            model_name='paiement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='id_emprunt',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='ouvrage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Ouvrage'),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Auteur'),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='autorisé',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='disponible',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='id_ouvrage',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='titre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='id_paiement',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type',
            field=models.CharField(blank=True, choices=[('a', 'Abonnement'), ('p', 'Pénalité')], help_text='Raison du paiement', max_length=1),
        ),
        migrations.AlterModelTable(
            name='emprunt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ouvrage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paiement',
            table=None,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
