# Generated by Django 2.2.7 on 2019-11-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premier_retard',
            field=models.DateTimeField(null=True),
        ),
    ]
