# Generated by Django 2.2.7 on 2019-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_auto_20191120_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='id_emprunt',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='auteur',
            name='id_auteur',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id_genre',
        ),
        migrations.RemoveField(
            model_name='ouvrage',
            name='id_ouvrage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_profile',
        ),
        migrations.AddField(
            model_name='auteur',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
