# Generated by Django 2.2.7 on 2019-11-21 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_auto_20191120_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pénalité',
            name='borrower',
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='borrower',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID pour cet emprunt', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='pénalité',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='genre',
            name='titre',
            field=models.CharField(help_text="Entrer le genre de l'ouvrage (e.g. Science Fiction)", max_length=100),
        ),
        migrations.RemoveField(
            model_name='ouvrage',
            name='genre',
        ),
        migrations.AddField(
            model_name='ouvrage',
            name='genre',
            field=models.ManyToManyField(help_text='Selectionner un genre pour cet ouvrage', to='gestion.Genre'),
        ),
        migrations.DeleteModel(
            name='BlackList',
        ),
        migrations.DeleteModel(
            name='Pénalité',
        ),
    ]
