# Generated by Django 2.2.7 on 2019-11-21 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prénom', models.CharField(max_length=100)),
                ('naissance', models.DateTimeField(blank=True, null=True)),
                ('mort', models.DateTimeField(blank=True, null=True, verbose_name='Mort')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Entrer le genre de l'ouvrage (e.g. Science Fiction)", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('statut', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('prix', models.IntegerField()),
            ],
            options={
                'db_table': 'Tarifs',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_retards', models.IntegerField(default=0)),
                ('premier_retard', models.DateTimeField(blank=True, null=True)),
                ('bad_user', models.IntegerField(default=0)),
                ('nb_livres', models.IntegerField(default=0)),
                ('nb_autres', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('nb_copies', models.IntegerField(default=1)),
                ('autorisé', models.IntegerField(default=1)),
                ('type', models.CharField(blank=True, choices=[('d', 'DVD'), ('v', 'Vinyl'), ('l', 'Livre'), ('c', 'CD')], help_text="Type d'ouvrage", max_length=1)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Auteur')),
                ('genre', models.ManyToManyField(help_text='Selectionner un genre pour cet ouvrage', to='gestion.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID pour cet emprunt', primary_key=True, serialize=False)),
                ('date_emprunt', models.DateTimeField()),
                ('retard', models.IntegerField(default=0)),
                ('pénalité', models.IntegerField(default=0)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Profile')),
                ('ouvrage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.Ouvrage')),
            ],
            options={
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
    ]
